releng:
  url: # set via EnvFile

jira1:
  host: # set via EnvFile
  username: # set via EnvFile
  password: # set via EnvFile

components-registry-service:
  url: # set via EnvFile

management:
  endpoints:
    web:
      exposure:
        include: health, env, metrics, threaddump, heapdump, info, configprops, prometheus, loggers
  endpoint:
    health:
      group:
        readiness:
          includes: legacyRelengIndicator, readinessState

logging:
  level:
    org.octopusden.octopus.releasemanagementservice.*: trace
